application: ghidonations
version: 5d
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30d"

handlers:

- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /apple-touch-icon-precomposed.png
  static_files: images/icons/apple-touch-icon-precomposed.png
  upload: images/icons/apple-touch-icon-precomposed.png

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /docs
  static_dir: docs

- url: /js
  static_dir: js

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

# Should be always secure
- url: /
  script: mooha.app
  secure: always

- url: /ajax/*.*
  script: mooha.app
  secure: optional

- url: /donate
  script: mooha.app
  secure: optional

# Should be always secure
- url: /ipn
  script: mooha.app
  secure: always

# Should be always secure
- url: /login
  script: mooha.app
  secure: always

- url: /logout
  script: mooha.app
  secure: optional

- url: /m/*.*
  script: mooha.app
  secure: optional

- url: /reports/.*
  script: mooha.app
  secure: optional

# Should be always secure
- url: /rpc
  script: rpc.app
  secure: always

- url: /_ah/spi/.*
  script: endpoints.app

- url: /tasks/.*
  script: tasks.app
  secure: optional
  login: admin

- url: /thanks
  script: mooha.app
  secure: optional


- url: /.*
  script: error.app
  secure: optional

error_handlers:
  - file: pages/error.html

builtins:
- deferred: on
- appstats: on

inbound_services:
- mail