application: ghidonations
version: 4d
runtime: python27
api_version: 1
threadsafe: no

default_expiration: "30d"

handlers:

- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /docs
  static_dir: docs

- url: /js
  static_dir: js

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

# Should be always secure
- url: /
  script: mooha.app
  secure: optional

- url: /ajax/*.*
  script: mooha.app
  secure: optional

- url: /donate
  script: mooha.app
  secure: optional

# Should be always secure
- url: /ipn
  script: mooha.app
  secure: optional

# Should be always secure
- url: /login
  script: mooha.app
  secure: optional

- url: /logout
  script: mooha.app
  secure: optional

- url: /m/*.*
  script: mooha.app
  secure: optional

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /reports/.*
  script: mooha.app
  secure: optional

# Should be always secure
- url: /rpc
  script: rpc.app
  secure: optional

- url: /tasks/.*
  script: tasks.app
  secure: optional
  login: admin

- url: /thanks
  script: mooha.app
  secure: optional


- url: /.*
  script: error.app
  secure: optional

error_handlers:
  - file: /pages/error.html

builtins:
- deferred: on
- remote_api: on
- appstats: on

inbound_services:
- mail