application: ghidonations
version: 6
runtime: python27
api_version: 1
threadsafe: false

default_expiration: "30d"

handlers:

# Static Files
- url: /favicon\.ico
  static_files: ghidonations/web/images/favicon.ico
  upload: ghidonations/web/images/favicon\.ico

- url: /apple-touch-icon-precomposed.png
  static_files: ghidonations/web/images/icons/apple-touch-icon-precomposed.png
  upload: ghidonations/web/images/icons/apple-touch-icon-precomposed.png

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /images
  static_dir: ghidonations/web/images

- url: /css
  static_dir: ghidonations/web/css

- url: /js
  static_dir: ghidonations/web/js


# Secured Endpoints
- url: /
  script: ghidonations.http_handlers.dispatch.app
  secure: always

- url: /ipn
  script: ghidonations.http_handlers.dispatch.app
  secure: always

- url: /login
  script: ghidonations.http_handlers.dispatch.app
  secure: always

- url: /rpc
  script: rpc.app
  secure: always


# Unsecured Endpoints
- url: /ajax/*.*
  script: ghidonations.http_handlers.dispatch.app
  secure: optional

- url: /donate
  script: ghidonations.http_handlers.dispatch.app
  secure: always

- url: /logout
  script: ghidonations.http_handlers.dispatch.app
  secure: optional

- url: /m/*.*
  script: ghidonations.http_handlers.dispatch.app
  secure: optional

- url: /reports/.*
  script: ghidonations.http_handlers.dispatch.app
  secure: optional

- url: /thanks
  script: ghidonations.http_handlers.dispatch.app
  secure: optional


# Task queue
- url: /tasks/.*
  script: tasks.app
  secure: optional
  login: admin


# API endpoints
- url: /_ah/pipeline(/.*)?
  script: pipeline.handlers.app

- url: /_ah/spi/.*
  script: ghidonations.rpc.ghiendpoints.app


# Admin Console
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin


# If nothing else matches, throw 404
# - url: /.*
#   script: error.app
#   secure: optional

error_handlers:
  - file: pages/error.html

builtins:
- deferred: on
- appstats: on

libraries:
- name: endpoints
  version: latest

inbound_services:
- mail